### ISSUE TITLE
Upgrading Projects to Visual Studio 2015

### ISSUE THREAD

**Issue by kevingy** [SimpleBrowserDotNet/SimpleBrowser#177]
I'm rebuilding my system and taking an inventory of what to re-install. The reason I have Visual Studio 2010 installed is Simple Browser development. Since it's 2016, perhaps it's time to upgrade. Any thoughts or concerns?

**Comment by Teun** [comment]
Yes, seems reasonable. I feel that the target platform for users of
SimpleBrowser should be as broad as possible, but for the development,
upgrading to a recent version of the tools is normal (especially since the
free version of VS is getting better with every version).


2016-07-11 20:43 GMT+02:00 Kevin Yochum <notifications@github.com>:

**Comment by kevingy** [comment]
Closing this issue in favor of #188. If we're going to upgrade, upgrade to the latest version (at this time 2017) rather than 2015.
