### ISSUE TITLE
Javascript enabled error

### ISSUE THREAD

**Issue by Ginger271** [SimpleBrowserDotNet/SimpleBrowser#179]
Is there anyway to avoid Javascript error and navigate to the next page? after click event browse returns the following html.

"<html><body>\r\n<p>Scripting is used to manage data interactions between the XXX server/Web Server and the User Interface. This requires JavaScript to be enabled  in the web browser </p>\r\n<p>To set this up in Internet Explorer, Please perform the following.</p>\r\n<p>Choose Tools > Internet Options > Security > Miscellaneous > set Active Scripting  to prompt or enable </p>\r\n<p>Choose Tools > Internet Options > Security > Miscellaneous > set Scripting of Java Applets  to prompt or enable </p>\r\n<p>For other browsers please follow equivalent instructions to enable JavaScri
pt use and to allow Java applets to interact with JavaScript. </p>\r\n</body>\r\n\r\n</html>\r\n"

**Comment by kevingy** [comment]
It depends. Without the URL of the page and the full source code, it is impossible give an exact answer.

That said, I've encountered pages like these before. Typically, JavaScript running in the browser will create a cookie or session value. When communication with the server occurs, server code then attempts to read the session or cookie value. If the cookie or session value isn't present or properly set, you get an error like the one you have posted.

To get around the error, you would need to reverse engineer the JavaScript and manually do whatever the JavaScript is doing. Since all JavaScript is executed browser-side, the server doesn't know if it's a JavaScript engine making the changes or if the client is setting values manually.

Can you give me more information on the URL you are trying to access? If it's a public web site, I may be able to offer assistance.

**Comment by kevingy** [comment]
Any luck? If no reply, I will assume you have resolved the problem and close this issue in 7 days,

**Comment by Ginger271** [comment]
hey Kevin, unfortunately its a private site and I cant share but I can explain what my requirement is and please let me know if am missing any steps:

1. Need to Navigate to a site
2. provide user name and password
3. Invoke button click
4. after the click event, the above html is returned by the browser object whereas when I test with fiddler from regular browser, I see SessionID and other information.
I cannot assign any  information to the browser object in the initial call as I dont get anything from login page.

Thanks.

**Comment by kevingy** [comment]
It sounds like you have step 1 and step 2 working properly. It's step 3 that's causing step 4 to return an unexpected result. When accessing the site with a regular browser, what happens when you click the button? Does the browser submit a form? Does the browser run JavaScript attached to the button that performs an AJAX call to the server? Does the browser run JavaScript to submit the form? Does the browser run JavaScript that injects form values? There are about half a dozen ways to program a browser button click. You would be surprised how creative programmers can be. :)

It sounds like a regular browser either performs an AJAX call or submits the form using JavaScript. When submitting using SimpleBrowser, SimpleBrowser performs a form submit instead. The server is trapping the form submit.

Even though it's a private site, can you send me just the JavaScript that's attached to the button? I can't imagine that would be a breach of privacy. Even though it's a private site, the server is still sending JavaScript to any client that requests it. It can't be _that_ private. All I would need is the JavaScript attached to the submit button - not even the full JavaSript.

I'm limited in how specific I can be without more detail.

**Comment by Ginger271** [comment]
Kevin,

Here is the  source of the login page and its doing post, looks like after
authentication the redirect page is validating whether JS enabled or not.

<html>
<head>

</head>
<body BGCOLOR="#ffffff" TEXT="#000000">

<IMG alt=Logo src="/ss.gif">


<form method=post><table>
<center>

<table width="50%" height=200 border=1 cellpadding=0 cellspacing=0 >
  <tr>
    <td>
 
      <table WIDTH="100%" HEIGHT=200 BGCOLOR="#6699ff" border=0
cellpadding=0 cellspacing=0 >

<tr>
 <td ALIGN="CENTER" VALIGN="CENTER" HEIGHT=40 COLSPAN=4 NOWRAP
BGCOLOR="#0C6AA1">
<font size="+1" face="Arial,Helvetica">
<b>Please Login </b></font>
     </td>
</tr>

<tr> <td colspan=4 height=10> <font size=1> &nbsp; </font> </td> </tr>

<tr>
 <td WIDTH=20 >&nbsp;</td>
 <td ALIGN="LEFT" >
   <b><font size=-1 face="arial,helvetica" > Username: </font></b>
 </td>
 <td ALIGN="LEFT" >
&nbsp; <input type="text" tabindex= "1" name="USER" size="30"
style="margin-left: 1px">
 </td>
 <td WIDTH=20 >&nbsp;</td>
</tr>

<tr> <td colspan=4 height=10> <font size=1> &nbsp; </font> </td> </tr>

<tr>
 <td WIDTH=20 >&nbsp;</td>
 <td >
   <b><font size=-1 face="arial,helvetica" > Password: </font></b>
     </td>
 <td ALIGN="left" >
&nbsp; <input type="password" tabindex= "2" name="PASSWORD" size="30"
style="margin-left: 1px">
 </td>
 <td WIDTH=20 >&nbsp;</td>
</tr>

<tr> <td colspan=4 height=10> <font size=1> &nbsp; </font> </td> </tr>
<tr>
 <td colspan=4 NOWRAP WIDTH="50%" HEIGHT="25" align="CENTER">
 <input type=hidden name=target value="https:/xxx/">
 <input type=hidden name=smauthreason value="0">
 <input type=hidden name=sname
value="4M48YGBkT9Db8NC6t1Mjdg0FvkcpB5W/cADdjPfTVum3QxTSgL8oBWEJuIO7esIa">
 <input type=hidden name=postpreservationdata value="">

 <input type=submit tabindex= "3" value="Login">
</td>
</tr>

<p>
<a href="https:/xx.jsp?task.tag=ForgottenPasswordReset"> Click here if you
forgot your password</a>
</p>

<p>
<a href="https:/xx/"> Click here to manage your password</a>
</p>

</table></form>
</center>
</body>
</html>

**Comment by kevingy** [comment]
Surprisingly, there is no JavaScript on the page, at least not in what you have provided. Assuming this is the full page content (modified for privacy, of course), the form is submitted by the browser. That being the case, I've trimmed all of the non-form stuff out, resulting in:
```
<form method=post>
<input type="text" tabindex= "1" name="USER" size="30" style="margin-left: 1px">
<input type="password" tabindex= "2" name="PASSWORD" size="30" style="margin-left: 1px">
<input type=hidden name=target value="https:/xxx/">
<input type=hidden name=smauthreason value="0">
<input type=hidden name=sname value="4M48YGBkT9Db8NC6t1Mjdg0FvkcpB5W/cADdjPfTVum3QxTSgL8oBWEJuIO7esIa">
<input type=hidden name=postpreservationdata value="">
<input type=submit tabindex= "3" value="Login">
</form>
```
The next thing to do is compare the HTML served to a typical browser and the HTML served to SimpleBrowser. In your C# code, just before the form submission use the Browser.CurrentHtml property to get the HTML SimpleBrowser has. Compare that HTML to the HTML you sent me. The important parts to look at are the input tags, particularly the hidden ones. The forms should match.

It just occurred to me that the problem may not be the form submission or the HTML content of the served form. There is a hidden input called "target" with a URL. After form submission, the page could use JavaScript to redirect to the "target" URL. (It seems like a hack, when the page should have sent a 3XX HTTP header, but like I said, programmers are "creative".) The same could be happening in a "regular browser," but happening so fast that you can't see it. You pasted HTML from Fiddler earlier. Was that the _entire_ result received or was there more?

**Comment by kevingy** [comment]
Any update?

**Comment by kevingy** [comment]
No response in 7 days. I'm going to assume this is no longer an issue. If that is not the case, please reopen the issue when you are ready to proceed.
