### ISSUE TITLE
 browser.RenderHtmlLogFile gives error

### ISSUE THREAD

**Issue by xpagedeveloper** [SimpleBrowserDotNet/SimpleBrowser#184]
When trying to use the function  browser.RenderHtmlLogFile I get that RazorHosting.dll doesn't exist.
If I add the nuget package for Razor I get 
The name 'WriteAttribute' does not exist in the current context

Any clues how to fix this problem ?

**Comment by kevingy** [comment]
I just ran a test using the sample program (which has a call to Browser.RenderHtmlLogFile). It worked fine for me:
![image](https://user-images.githubusercontent.com/411556/27547841-32748080-5a65-11e7-95b4-80d23bd6c33b.png)

You're going to have to give me more information to go on to help with the problem you are experiencing. Are you running the sample program as well - or is the call to RenderHtmlLogFile in your own code? What version of Visual Studio? What OS?

**Comment by xpagedeveloper** [comment]
I have visual studio 2015 with Windows 10 creators edision.
I added your sample code into a Windows forms App and downloaded simple browser using nuget

**Comment by kevingy** [comment]
I haven't forgotten about this issue. I simply haven't had time to set up a test. Your environment should work (although the SimpleBrowser Nuget package is a bit dated).

**Comment by xpagedeveloper** [comment]
So what is the best way to implement simple browser in a project ?

**Comment by kevingy** [comment]
It really should be as simple as what is in the sample project. I would either fork or clone the SimpleBrowser repository to get the latest changes. (That said, I'm a developer on the project. A typical user's perspective may vary.) Regardless of using Nuget or not, add a reference to SimpleBrowser in the consuming application, add a using, declare a Browser object and go. It shouldn't take more than that, which is why I'm surprised you're getting an error.

**Comment by xpagedeveloper** [comment]
I got this to work now by doing the following steps
Remove the nuget reference in the project file (Otherwise would VS2015 import it)
Import this project into my project and adding a reference to Simple Browser from my existing project.

Thanks alot kevingy
