### ISSUE TITLE
Cookies - Google websites

### ISSUE THREAD

**Issue by Davidkulpe** [SimpleBrowserDotNet/SimpleBrowser#191]
Hi,
I'm using this amazing product to do some automatic daily tasks, for Google products I cannot sign-In using SimpleBrowser, the Google Sign-In screens state  the browser doesn't support cookies

![capture](https://user-images.githubusercontent.com/3175897/34078479-e50a1952-e323-11e7-8bd3-ff5d91f6904b.PNG)

Any idea?
.

**Comment by kevingy** [comment]
Hi @Davidkulpe,

Despite what the message says, the problem isn't cookies. The problem is JavaScript. Google uses JavaScript in their sign in process to set cookie values. When the page can't find the cookies set by JavaScript, because the JavaScript didn't run, it throws the cookie error.

Unfortunately, I don't think that there is a way to get around that.

Kevin

**Comment by Davidkulpe** [comment]
Thanks for the reply.
I really hope you'll add JavaScript support someday, I worked with many browsers, I find SimpleBrowser to be amazing...
Great Job
