### ISSUE TITLE
Getting Error on Found Same name

### ISSUE THREAD

**Issue by blackbuzz4rd** [SimpleBrowserDotNet/SimpleBrowser#193]
24-Jan-2018 5:11.219 AM
New HTML result set obtained, containing 2 element(s)
24-Jan-2018 5:11.219 AM

```
Clicking element: <button type="submit" name="send" class="button-wrapper"> <span class="button-wrapper__valign" /> <span class="button"> <span class="button__inner"> <span class="button__valign" />Send</span> </span> </button>
24-Jan-2018 5:11.238 AM
The path is not of a legal form.
```
`
2 Send Buttons with same name.

HTML source : https://jsfiddle.net/y7edrdL7/

I could Not Fix it. How can I solve it?

**Comment by kevingy** [comment]
There are actually few ways to approach this.

1. Browser.Find() returns an HtmlResult. HtmlResult contains a list of the find results. Assuming you are searching the HTML using Find(FindBy.Name), you would get an HtmlResult that contains two buttons. You would then need to know which item (index 0 or index 1) in the result to click.

2. Browser.Find() returns an HtmlResult. HtmlResult contains a list of the find results. Assuming you are searching the HTML using FindBy(FindBy.Name), you would get an HtmlResult that contains two buttons. Use HtmlResult.Refine() to further specify the search result.

3. Instead of searching elements by name, search by class. There is only one send button with class="button-wrapper". **This is probably your best option.** For example:

`var result = Find("button", FindBy.Class, "button-wrapper");`

4. Similar to the above, but with different syntax:

`var result = Find(ElementType.Button, "class", "button-wrapper");`

Now that I have written all of this, I'm questioning what the problem is that you are reporting. Is the problem that you are having difficulty selecting the correct button to click _or_ is the problem that you have found the correct button to click, but when you click it, SimpleBrowser sends both buttons in the form submission?

Kevin

**Comment by blackbuzz4rd** [comment]
Thanks for your reply. I can select the correct button. But after submitting click I always get it. I'm a VB guy :P 

`

                                     Dim searchLogout As HtmlResult = WBbrowser.Find("button", New With {Key .[class] = "button-wrapper", Key .type = "submit", Key .name = "send"})

                                     If Not (searchLogout.Exists = False) Then

                                         searchLogout.Click()

                                     End If
`


`
`
-- 
Elizaweta Zashibalova
&lt;/textarea&gt; to Thisn is some message55
New HTML result set obtained, containing 1 element(s)
Clicking element: &lt;button type=&quot;submit&quot; name=&quot;send&quot; class=&quot;button-wrapper&quot;&gt; &lt;span class=&quot;button-wrapper__valign&quot; /&gt; &lt;span class=&quot;button&quot;&Exception thrown: 'System.ArgumentException' in mscorlib.dll
gt; &lt;span class=&quot;button__inner&quot;&gt; &lt;span class=&quot;button__valign&quot; /&gt;Send&lt;/span&gt; &lt;/span&gt; &lt;/button&gt;
The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at SimpleBrowser.Elements.FormElement.Submit(String url, HtmlElement clickedElement) in G:\vs\vb.net\mailsendersb\SimpleBrowser\SimpleBrowser\Elements\FormElement.cs:line 148
   at SimpleBrowser.Elements.FormElement.SubmitForm(String url, HtmlElement clickedElement) in G:\vs\vb.net\mailsendersb\SimpleBrowser\SimpleBrowser\Elements\FormElement.cs:line 108
   at SimpleBrowser.HtmlElement.SubmitForm(String url, HtmlElement clickedElement) in G:\vs\vb.net\mailsendersb\SimpleBrowser\SimpleBrowser\HtmlElement.cs:line 235
   at SimpleBrowser.Elements.B'MailSenderSB.exe' (CLR v4.0.30319: MailSenderSB.exe): Loaded 'G:\vs\vb.net\mailsendersb\SimpleBrowser\MailSenderSB\bin\Debug\RazorHosting.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.IO.FileNotFoundException' in RazorHosting.dll
uttonInputElement.Click() in G:\vs\vb.net\mailsendersb\SimpleBrowser\SimpleBrowser\Elements\ButtonInputElement.cs:line 53
   at SimpleBrowser.HtmlResult.Click() in G:\vs\vb.net\mailsendersb\SimpleBrowser\SimpleBrowser\HtmlResult.cs:line 279
   at MailSenderSB.MailSender._Lambda$__18-0() in G:\vs\vb.net\mailsendersb\SimpleBrowser\MailSenderSB\MailSender.vb:line 128

`
`

**Comment by kevingy** [comment]
The last line of SimpleBrowser code that runs before the crash is:

> at SimpleBrowser.Elements.FormElement.Submit(String url, HtmlElement clickedElement) in G:\vs\vb.net\mailsendersb\SimpleBrowser\SimpleBrowser\Elements\FormElement.cs:line 148

That section of code deals with submitting binary files in the form submission. (That is, the problem isn't the duplicate named send button.) The error message from the exception is:

> The path is not of a legal form.

Are you entering any path into the form? If so, what is that path?

**Comment by blackbuzz4rd** [comment]
I only fill up 3 fields. To, Subject and Message.

**Comment by blackbuzz4rd** [comment]
You May Check this https://jsfiddle.net/jgrxjqwm/

**Comment by kevingy** [comment]
Using your Fiddles and running a couple tests, this looks like it may be a problem in SimpleBrowser. I'll set up a more complex test to make that determination. If it is SimpleBrowser, I'll be able to use the test scenario to debug as well.

**Comment by blackbuzz4rd** [comment]
Thanks a lot. I'm Waiting for the Fix :)

**Comment by kevingy** [comment]
I think I've fixed the problem. Would you mind pulling the change from my fork to test? I've run the unit tests and performed my own testing. It looks good, but before I accept the pull request, another person looking at the changes would be good. My fork is:

https://github.com/kevingy/SimpleBrowser

Thanks!

**Comment by blackbuzz4rd** [comment]
OMG it's Working. Thanks!

**Comment by kevingy** [comment]
Thanks. I'll merge the pull request into the SimpleBrowser repository.
