### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by GerhardKreuzer** [SimpleBrowserDotNet/SimpleBrowser#220]
Dear Team,

sorry, but the sample with github doesnt work ...
Is there any other simple sample for a newbee out ??

With best regards

Gerhard

**Comment by Shahmeerm** [comment]
@kevingy Will you accept PR for new Sample ? Let me know. Thank you!

**Comment by kevingy** [comment]
@Shahmeerm Yes, pull requests are always welcome.

**Comment by kevingy** [comment]
@GerhardKreuzer When you say it "doesn't work", are you seeing a 301 error with the error message "An exception was thrown while trying to load the page: The request was aborted: Could not create SSL/TLS secure channel."?

If so, I have a fix for that.

**Comment by kevingy** [comment]
I'm adding more detail here for posterity.

 SSL is dying and being replaced by TLS. First, browsers stopped supporting SSL. Now, web servers are disabling SSL. The root cause of this issue was github.com no longer supports SSL. SimpleBrowser uses .NET Framework, which uses SSL by default. Since github wanted to use TLS and SimpleBrowser wanted to use SSL, they couldn't talk to each other.

I updated SimpleBrowser to use TLS by default (like Chrome). I also added the ability for the SimpleBrowser to change the default.
