### ISSUE TITLE
RenderHtmlLogFile method missing.

### ISSUE THREAD

**Issue by MagicBOTAlex** [SimpleBrowserDotNet/SimpleBrowser#257]
![image](https://user-images.githubusercontent.com/44818698/101968349-0fb36580-3c1f-11eb-889e-58048b68dd3d.png)
System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1<System.String> RazorLight.RazorLightEngine.CompileRenderAsync(System.String, System.String, !!0, System.Dynamic.ExpandoObject)'.'

I don't know what this means but I have tried reinstalling the addon twice. but no luck

**Comment by kevingy** [comment]
What does "tried reinstalling the addon twice" mean? Does that mean you installed the NuGet package twice?

**Comment by BOTAlex321** [comment]
Uninstalling and then installing the package using nuget

**Comment by kevingy** [comment]
Looking at the error more closely, it looks like what is missing is not RenderHtmlLogFile. Rather, it looks like a dependency is missing - RazorLight.RazorLightEngine. You shouldn't have to, but try installing that nuget package as well and see if the error goes away.

In general, the nuget package is ancient. I recommend pulling the master branch from the repository.

**Comment by NJCCJohnWason** [comment]
> 
> 
> Looking at the error more closely, it looks like what is missing is not RenderHtmlLogFile. Rather, it looks like a dependency is missing - RazorLight.RazorLightEngine. You shouldn't have to, but try installing that nuget package as well and see if the error goes away.
> 
> In general, the nuget package is ancient. I recommend pulling the master branch from the repository.

In nuget version is 2019,what should I do to get new version extension?

**Comment by kevingy** [comment]
The only way to get the current version is to clone the master branch of the SimpleBrowser repository from Github. You can either include the project into your solution and include a project reference in your project -or- build SimpleBrowser independently and include the resulting DLL in your project.

I'll try to spend some time this weekend on the project to fix the Nuget package. It has been so long since I've tried that I don't recall what the issue was with updating the package in the package repository.
