### ISSUE TITLE
SimpleBrowser adds duplicated "name" attribute with an incorrect value.

### ISSUE THREAD

**Issue by guokas** [SimpleBrowserDotNet/SimpleBrowser#270]
I have an HTML page, in the Chrome browser it shows as follows:
&lt;select size="1" **name="ct100$ContentPlaceHolder1$SelectTipo"**  id = "ct100_ContentPlaceHolder1_SelectTipo" class="Caixa_Texto" onchange="addSelectValueHidden();"&gt;
&lt;option value="value1"&gt;item1</option&gt;
&lt;option value="value2"&gt;item2</option&gt;
&lt;/select&gt;

but when I load it to SimpleBrowser, it adds an additional "**name**" attribute with a false value.
&lt;select size="1" **name="ct100$ContentPlaceHolder1$SelectTipo"**  id = "ct100_ContentPlaceHolder1_SelectTipo" **name="SelectTipo"** class="Caixa_Texto" onchange="addSelectValueHidden();"&gt;
&lt;option value="value1">item1</option&gt;
&lt;option value="value2">item2</option&gt;
&lt;/select&gt;

When I invoke `objHtmlElement.XElement.GetAttribute("name")`, it returns `SelectTipo `instead of `ct100$ContentPlaceHolder1$SelectTipo`
****

SimpleBrowser Version: 0.57.9

**Comment by kevingy** [comment]
The behavior you are describing is the expected behavior. 

`<select size="1" name="ct100$ContentPlaceHolder1$SelectTipo" id = "ct100_ContentPlaceHolder1_SelectTipo" name="SelectTipo" class="Caixa_Texto" onchange="addSelectValueHidden();">`

The value of the name attribute is "SelectTipo". The value of the id attribute is "ct100_ContentPlaceHolder1_SelectTipo". If you expect "ct100_ContentPlaceHolder1_SelectTipo", you need `objHtmlElement.XElement.GetAttribute("id")`.
